<?xml version="1.0" encoding="UTF-8"?>
<testsuite errors="0" failures="0" file="Publish_tests.py" name="Publish_tests.PublishTest-20191030161117" skipped="0" tests="2" time="0.003" timestamp="2019-10-30T16:11:17">
	<testcase classname="Publish_tests.PublishTest" file="src/unittest/python/Publish_tests.py" line="12" name="testCanPublish" time="0.001" timestamp="2019-10-30T16:11:17">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
	<testcase classname="Publish_tests.PublishTest" file="src/unittest/python/Publish_tests.py" line="18" name="testDescription" time="0.002" timestamp="2019-10-30T16:11:17">
		<system-out>
<![CDATA[]]>		</system-out>
		<system-err>
<![CDATA[]]>		</system-err>
	</testcase>
</testsuite>
